server:
  port: 8001 #端口号
  servlet:
    context-path: /helloworld #访问路径

# 热部署
# 1、File-Settings-Compiler-Build Project automatically
# 2、ctrl + shift + alt + /,1、Registry,2、Compiler autoMake allow when app running
spring:
  devtools:
    restart:
      enabled: true #是否开启热部署
      additional-paths: src/main/java # 修改那个目录下的文件

